# K-nearest neighbors

The K-nears neighbors or the KNN looks at the variable closes to the analyzed variable. In this case the variable: S1 goed which means Symptom 1 correct.

In [35]:
import seaborn as sns
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [36]:
df = pd.read_excel("Predictions.xlsx")
df.head(30)

,UserNr,Studierichting,S1 goed,S1 fout,S2 goed,S2 fout,S3 goed,S3 fout,S4 goed,S4 fout
0,1,Exact en informatica,7,3,9,1,9,1,1,9
1,2,Recht en bestuur,7,3,10,0,5,5,8,2
2,3,Recht en bestuur,6,4,9,1,4,6,1,9
3,4,Exact en informatica,0,10,0,10,1,9,5,5
4,5,Taal en communicatie,2,8,8,2,5,5,2,8
5,6,Taal en communicatie,5,5,0,10,8,2,10,0
6,7,Taal en communicatie,8,2,7,3,6,4,1,9
7,8,Aarde en milieu,2,8,10,0,3,7,6,4
8,9,Gezondheid,9,1,0,10,2,8,8,2
9,10,Kunst en cultuur,7,3,7,3,9,1,6,4
10,11,Kunst en cultuur,1,9,9,1,0,10,10,0
11,12,Gezondheid,0,10,1,9,1,9,8,2
12,13,Exact en informatica,4,6,8,2,3,7,9,1
13,14,Aarde en milieu,9,1,1,9,2,8,1,9
14,15,Aarde en milieu,2,8,0,10,1,9,5,5
15,16,Recht en bestuur,6,4,8,2,5,5,0,10
16,17,Recht en bestuur,4,6,0,10,6,4,10,0
17,18,Exact en informatica,9,1,3,7,1,9,8,2
18,19,Taal en communicatie,0,10,2,8,2,8,6,4
19,20,Gezondheid,6,4,10,0,10,0,4,6
20,21,Aarde en milieu,3,7,7,3,2,8,6,4
21,22,Kunst en cultuur,7,3,0,10,9,1,3,7
22,23,Recht en bestuur,2,8,7,3,0,10,1,9
23,24,Onderwijs en opvoeding,4,6,3,7,4,6,5,5
24,25,Techniek,2,8,3,7,6,4,8,2
25,26,Gezondheid,10,0,5,5,0,10,10,0
26,27,Exact en informatica,3,7,4,6,7,3,9,1
27,28,Recht en bestuur,0,10,9,1,5,5,8,2
28,29,Taal en communicatie,7,3,7,3,9,1,2,8
29,30,Interdisciplinair,1,9,3,7,9,1,10,0

In [37]:
dummies = pd.get_dummies(df['Studierichting'])
df = pd.concat([df, dummies], axis=1) #the axis=1 means: add it to the columns (axis=0 is rows)
df.head()

,UserNr,Studierichting,S1 goed,S1 fout,S2 goed,S2 fout,S3 goed,S3 fout,S4 goed,S4 fout,...,Economie en bedrijf,Exact en informatica,Gedrag en maatschappij,Gezondheid,Interdisciplinair,Kunst en cultuur,Onderwijs en opvoeding,Recht en bestuur,Taal en communicatie,Techniek
0,1,Exact en informatica,7,3,9,1,9,1,1,9,...,0,1,0,0,0,0,0,0,0,0
1,2,Recht en bestuur,7,3,10,0,5,5,8,2,...,0,0,0,0,0,0,0,1,0,0
2,3,Recht en bestuur,6,4,9,1,4,6,1,9,...,0,0,0,0,0,0,0,1,0,0
3,4,Exact en informatica,0,10,0,10,1,9,5,5,...,0,1,0,0,0,0,0,0,0,0
4,5,Taal en communicatie,2,8,8,2,5,5,2,8,...,0,0,0,0,0,0,0,0,1,0

In [38]:
X = df[['S2 goed', 'S3 goed', 'S4 goed', 'Aarde en milieu', 'Economie en bedrijf', 'Exact en informatica', 
        'Gedrag en maatschappij', 'Gezondheid', 'Interdisciplinair', 'Kunst en cultuur', 'Onderwijs en opvoeding', 
        'Recht en bestuur', 'Taal en communicatie', 'Techniek']] 

y = df['S1 goed'] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 

X_train.head()

,S2 goed,S3 goed,S4 goed,Aarde en milieu,Economie en bedrijf,Exact en informatica,Gedrag en maatschappij,Gezondheid,Interdisciplinair,Kunst en cultuur,Onderwijs en opvoeding,Recht en bestuur,Taal en communicatie,Techniek
13,1,2,1,1,0,0,0,0,0,0,0,0,0,0
61,3,9,5,0,0,0,0,0,0,0,1,0,0,0
298,1,7,6,0,0,0,0,0,0,0,1,0,0,0
39,8,10,0,0,1,0,0,0,0,0,0,0,0,0
360,8,3,5,0,0,0,1,0,0,0,0,0,0,0

In [39]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors=3)
knn = knn.fit(X_train, y_train)

In [40]:
knn.score(X_test, y_test)

0.08666666666666667

In [41]:
from sklearn.metrics import confusion_matrix
y_test_pred = knn.predict(X_test)
cm = confusion_matrix(y_test, y_test_pred) 
cm

array([[1, 5, 4, 2, 0, 0, 3, 0, 0, 0, 0],
       [1, 2, 3, 2, 1, 1, 1, 0, 0, 0, 0],
       [0, 5, 2, 6, 1, 1, 0, 0, 0, 0, 0],
       [2, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0],
       [3, 4, 3, 2, 2, 2, 0, 0, 0, 0, 0],
       [1, 4, 2, 3, 0, 2, 1, 0, 0, 0, 0],
       [3, 5, 1, 2, 1, 0, 0, 0, 0, 0, 0],
       [2, 3, 3, 1, 2, 2, 0, 0, 2, 2, 0],
       [2, 3, 4, 2, 2, 1, 0, 2, 2, 0, 0],
       [2, 1, 1, 2, 3, 1, 0, 0, 0, 1, 0],
       [1, 6, 3, 2, 1, 0, 1, 0, 0, 0, 0]])

In [42]:
knn.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
conf_matrix = pd.DataFrame(cm, index=['S1 0 goed (actual)', 'S1 1 goed (actual)', 'S1 2 goed (actual)', 'S1 3 goed (actual)', 'S1 4 goed (actual)', 'S1 5 goed (actual)', 'S1 6 goed (actual)', 'S1 7 goed (actual)', 'S1 8 goed (actual)', 'S1 9 goed (actual)', 'S1 10 goed (actual)'], columns = ['S1 0 goed (predicted)', 'S1 1 goed (predicted)', 'S1 2 goed (predicted)', 'S1 3 goed (predicted)', 'S1 4 goed (predicted)', 'S1 5 goed (predicted)', 'S1 6 goed (predicted)', 'S1 7 goed (predicted)', 'S1 8 goed (predicted)', 'S1 9 goed (predicted)', 'S1 10 goed (predicted)']) #make a dataframe, put labels on rows (index) and columns 
conf_matrix

,S1 0 goed (predicted),S1 1 goed (predicted),S1 2 goed (predicted),S1 3 goed (predicted),S1 4 goed (predicted),S1 5 goed (predicted),S1 6 goed (predicted),S1 7 goed (predicted),S1 8 goed (predicted),S1 9 goed (predicted),S1 10 goed (predicted)
S1 0 goed (actual),1,5,4,2,0,0,3,0,0,0,0
S1 1 goed (actual),1,2,3,2,1,1,1,0,0,0,0
S1 2 goed (actual),0,5,2,6,1,1,0,0,0,0,0
S1 3 goed (actual),2,2,1,1,0,1,1,0,0,0,0
S1 4 goed (actual),3,4,3,2,2,2,0,0,0,0,0
S1 5 goed (actual),1,4,2,3,0,2,1,0,0,0,0
S1 6 goed (actual),3,5,1,2,1,0,0,0,0,0,0
S1 7 goed (actual),2,3,3,1,2,2,0,0,2,2,0
S1 8 goed (actual),2,3,4,2,2,1,0,2,2,0,0
S1 9 goed (actual),2,1,1,2,3,1,0,0,0,1,0
S1 10 goed (actual),1,6,3,2,1,0,1,0,0,0,0